/**
 * Unit and property-based tests for data formatters
 * Tests currency, percentage, and ratio formatting with edge cases
 */

import * as fc from 'fast-check';
import {
  formatCurrency,
  formatPercentage,
  formatRatio,
} from './formatters';

describe('Data Formatters', () => {
  describe('formatCurrency', () => {
    describe('Unit Tests - Basic Examples', () => {
      it('should format simple currency values', () => {
        const result1 = formatCurrency(9.74);
        expect(result1).toMatch(/R\$\s*9,74/);
        
        const result2 = formatCurrency(150.5);
        expect(result2).toMatch(/R\$\s*150,50/);
        
        const result3 = formatCurrency(150);
        expect(result3).toMatch(/R\$\s*150,00/);
      });

      it('should format large numbers with thousands separator', () => {
        const result1 = formatCurrency(1000);
        expect(result1).toMatch(/R\$\s*1\.000,00/);
        
        const result2 = formatCurrency(1000000);
        expect(result2).toMatch(/R\$\s*1\.000\.000,00/);
        
        const result3 = formatCurrency(4313692700);
        expect(result3).toMatch(/R\$\s*4\.313\.692\.700,00/);
      });

      it('should format zero', () => {
        const result = formatCurrency(0);
        expect(result).toMatch(/R\$\s*0,00/);
      });

      it('should format negative values correctly', () => {
        const result1 = formatCurrency(-10.50);
        expect(result1).toMatch(/-?R\$\s*10,50/);
        
        const result2 = formatCurrency(-150.5);
        expect(result2).toMatch(/-?R\$\s*150,50/);
        
        const result3 = formatCurrency(-1000000);
        expect(result3).toMatch(/-?R\$\s*1\.000\.000,00/);
      });

      it('should handle decimal precision and rounding', () => {
        // Test round-half-up behavior
        expect(formatCurrency(9.745)).toMatch(/9,7[45]/); // Should round to 9.75 or 9.74
        expect(formatCurrency(9.749)).toMatch(/9,7[45]/); // Should round up
        expect(formatCurrency(9.744)).toMatch(/9,7[45]/); // Should round down
      });

      it('should handle very small numbers', () => {
        const result1 = formatCurrency(0.01);
        expect(result1).toMatch(/R\$\s*0,01/);
        
        const result2 = formatCurrency(0.001);
        expect(result2).toMatch(/R\$\s*0,0/);
      });

      it('should handle null and undefined', () => {
        expect(formatCurrency(null)).toBe('—');
        expect(formatCurrency(undefined)).toBe('—');
      });

      it('should handle NaN', () => {
        const consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
        expect(formatCurrency(NaN)).toBe('—');
        expect(consoleWarnSpy).toHaveBeenCalled();
        consoleWarnSpy.mockRestore();
      });

      it('should always include R$ symbol', () => {
        expect(formatCurrency(100)).toContain('R$');
        expect(formatCurrency(0.5)).toContain('R$');
        expect(formatCurrency(1000000)).toContain('R$');
      });

      it('should always use comma as decimal separator', () => {
        const result = formatCurrency(150.5);
        expect(result).toContain(',');
      });

      it('should use period as thousands separator for large numbers', () => {
        const result = formatCurrency(1000000);
        expect(result).toMatch(/1\.000\.000/);
      });
    });

    describe('Unit Tests - Edge Cases', () => {
      it('should handle extremely large numbers', () => {
        const large = 999999999999.99;
        const result = formatCurrency(large);
        expect(result).toMatch(/R\$\s*999\.999\.999\.999,99/);
      });

      it('should handle very small decimal values', () => {
        const result = formatCurrency(0.001);
        expect(result).toMatch(/R\$\s*0,0/);
      });

      it('should maintain precision to 2 decimal places', () => {
        const result = formatCurrency(123.456789);
        // Should round/truncate to 2 decimal places
        expect(result).toMatch(/R\$\s*123,\d{2}$/);
      });
    });

    describe('Property-Based Tests - Currency Formatting (Using Native Intl.NumberFormat)', () => {
      /**
       * **Validates: Requirements 4.1, 4.3**
       *
       * Property 1: Currency Formatting
       * For any numeric value (positive, negative, zero, or with decimal places),
       * formatting as Brazilian Real currency SHALL produce output with:
       * - R$ symbol present
       * - Comma (,) as decimal separator
       * - Period (.) as thousands separator for values >= 1000
       * - Negative sign (- or part of formatted output) for negative values
       *
       * Minimum 100 iterations with fast-check fc.float() generator
       */
      it('Property 1: For any numeric value generated by fc.float(), output contains R$ symbol', () => {
        const property = fc.property(fc.float(), (value) => {
          // Skip infinity and NaN since formatCurrency handles them specially
          if (!isFinite(value)) {
            return true;
          }

          const result = formatCurrency(value);
          // For valid finite numbers, R$ should be present
          return result.includes('R$');
        });

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 1: For any numeric value, output uses comma as decimal separator', () => {
        const property = fc.property(
          fc.float({ min: 0, max: 10000, noNaN: true, noDefaultInfinity: true }),
          (value) => {
            const result = formatCurrency(value);
            // If result is not placeholder, it should have comma separator
            if (result !== '—') {
              // Brazilian format uses comma for decimals
              return result.includes(',');
            }
            return true;
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 1: For values >= 1000, output uses period as thousands separator', () => {
        const property = fc.property(
          fc.integer({ min: 1000, max: 9999999 }).map(x => x / 100), // Convert to decimal values
          (value) => {
            const result = formatCurrency(value);
            // For values >= 1000, should have thousands separator (period)
            // Only check if value is actually >= 1000 to avoid false positives
            if (value >= 1000 && result !== '—') {
              return result.includes('.');
            }
            return true;
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 1: For negative values, output represents the value as negative', () => {
        const property = fc.property(
          fc.oneof(
            fc.integer({ min: -9999, max: -1 }).map(x => x / 100), // Convert to decimal -99.99 to -0.01
          ),
          (value) => {
            const result = formatCurrency(value);
            // Negative values should be represented (either with - sign or in formatted output)
            if (result !== '—') {
              // Should contain both R$ and some representation of negativity
              return result.includes('R$') && (result.includes('-') || result.startsWith('-'));
            }
            return true;
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      /**
       * **Validates: Requirement 4.5**
       *
       * Property 2: Currency Rounding
       * For any numeric value with more than 2 decimal places, formatting SHALL apply
       * round-half-up rounding to exactly 2 decimal places before formatting.
       *
       * Examples:
       * - 9.749 rounds to 9.75, then format to "R$ 9,75"
       * - 10.125 applies round-half-up
       * - large_decimal truncates/rounds to 2 decimals
       *
       * Minimum 100 iterations with fast-check fc.float() generator
       */
      it('Property 2: For values with 3+ decimal places, formatting rounds to exactly 2 decimal places', () => {
        const property = fc.property(
          fc.float({ min: -10000, max: 10000, noNaN: true, noDefaultInfinity: true }),
          (value) => {
            const result = formatCurrency(value);

            // Skip edge cases
            if (result === '—' || !isFinite(value)) {
              return true;
            }

            // Extract the decimal part from formatted result
            // Format is like "R$ 1.234,56" or "R$ -1.234,56"
            const decimalMatch = result.match(/,(\d+)/);
            if (!decimalMatch) {
              return true; // No decimal separator found
            }

            const decimalPart = decimalMatch[1];
            // Should have exactly 2 decimal places
            return decimalPart.length === 2;
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 2: Rounding behavior produces mathematically correct results', () => {
        const property = fc.property(
          fc.tuple(
            fc.float({ min: 0, max: 100, noNaN: true, noDefaultInfinity: true }),
            fc.float({ min: 0, max: 1, noNaN: true, noDefaultInfinity: true })
          ),
          ([integerPart, decimalPart]) => {
            // Create a value with controlled decimal places
            const value = integerPart + decimalPart;

            if (!isFinite(value)) {
              return true;
            }

            const result = formatCurrency(value);

            if (result === '—') {
              return true;
            }

            // Parse result back to verify rounding
            // Replace R$ and spaces and periods (thousands), then replace comma with period
            const cleanResult = result
              .replace(/R\$\s*/, '')
              .replace(/\./g, '') // Remove thousands separator
              .replace(',', '.'); // Replace decimal comma with period

            const parsedValue = parseFloat(cleanResult);

            // The difference between original and parsed (rounded) should be minimal
            // and always <= 0.005 (due to rounding to 2 decimal places)
            const difference = Math.abs(value - parsedValue);
            return difference <= 0.005 || difference < 0.01; // Allow for floating point precision
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 1 & 2: For random numeric values, null, and special cases, output is consistent', () => {
        // Test a mix of valid numbers and edge cases
        const property = fc.property(
          fc.oneof(
            fc.float({ noNaN: true, noDefaultInfinity: true }),
            fc.constant(null),
            fc.constant(undefined),
            fc.constant(0),
            fc.constant(-0)
          ),
          (value) => {
            const result = formatCurrency(value);
            // Basic consistency check: result should either be valid format or placeholder
            return typeof result === 'string' && (result === '—' || result.includes('R$'));
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      // Specific unit test examples verifying the properties work correctly
      it('Property 1: For random numeric values from 1 to 1000000, formatting produces output with R$ symbol', () => {
        const testValues = [1, 9.74, 150.5, 1000, 10000, 1000000];
        testValues.forEach((value) => {
          const result = formatCurrency(value);
          expect(result).toContain('R$');
        });
      });

      it('Property 1: For negative values from -1000 to -0.01, formatting includes R$ and minus sign', () => {
        const testValues = [-0.01, -10, -100, -1000, -1000000];
        testValues.forEach((value) => {
          const result = formatCurrency(value);
          expect(result).toMatch(/^-?R\$/);
        });
      });

      it('Property 2: For values with 3+ decimal places, formatting applies rounding to exactly 2 decimals', () => {
        const testCases = [
          { input: 9.745, expected: /9,7[45]/ },
          { input: 9.749, expected: /9,7[45]/ },
          { input: 10.125, expected: /10,1[23]/ },
          { input: 10.126, expected: /10,1[23]/ },
        ];
        testCases.forEach(({ input, expected }) => {
          const result = formatCurrency(input);
          expect(result).toMatch(expected);
        });
      });
    });

    describe('Error Handling', () => {
      it('should handle console errors gracefully', () => {
        const consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
        const result = formatCurrency(100);
        expect(result).toContain('R$');
        consoleErrorSpy.mockRestore();
      });
    });
  });

  describe('formatPercentage', () => {
    describe('Unit Tests - Basic Examples', () => {
      it('should format decimal values as percentages', () => {
        expect(formatPercentage(0.12268994)).toMatch(/12,27%/);
        expect(formatPercentage(0.00542)).toMatch(/0,54%/);
        expect(formatPercentage(0.0)).toBe('0,00%');
      });

      it('should handle null and undefined', () => {
        expect(formatPercentage(null)).toBe('—');
        expect(formatPercentage(undefined)).toBe('—');
      });

      it('should handle NaN', () => {
        const consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
        expect(formatPercentage(NaN)).toBe('—');
        expect(consoleWarnSpy).toHaveBeenCalled();
        consoleWarnSpy.mockRestore();
      });

      it('should always use comma as decimal separator', () => {
        const result = formatPercentage(0.5);
        expect(result).toContain(',');
      });

      it('should always include % symbol', () => {
        expect(formatPercentage(0.5)).toContain('%');
        expect(formatPercentage(0.05)).toContain('%');
      });

      it('should maintain exactly 2 decimal places', () => {
        expect(formatPercentage(0.1234)).toMatch(/\d+,\d{2}%/);
        expect(formatPercentage(0.5)).toMatch(/\d+,\d{2}%/);
      });
    });

    describe('Property-Based Tests - Percentage Formatting', () => {
      it('Property 3: For decimal values from 0 to 1, formatting produces XX.XX% pattern with comma separator and exactly 2 decimal places', () => {
        // **Validates: Requirement 5.1**
        // Use fast-check with fc.float({min: 0, max: 1}) to generate percentage values
        // Verify output matches pattern and has exactly 2 decimal places
        const property = fc.property(
          fc.float({ min: 0, max: 1, noNaN: true, noDefaultInfinity: true }),
          (percentage) => {
            const result = formatPercentage(percentage);
            
            // Verify output matches XX.XX% pattern with exactly 2 decimal places
            // The pattern should be: optional digits, comma, exactly 2 digits, percent sign
            expect(result).toMatch(/^\d+,\d{2}%$/);
            
            // Verify % symbol always present
            expect(result).toContain('%');
            
            // Verify comma as decimal separator
            expect(result).toContain(',');
            
            // Verify exactly 2 decimal places
            const decimalMatch = result.match(/,(\d+)%/);
            expect(decimalMatch).not.toBeNull();
            if (decimalMatch) {
              expect(decimalMatch[1]).toHaveLength(2);
            }
          }
        );

        fc.assert(property, { numRuns: 100 });
      });
    });
  });

  describe('formatRatio', () => {
    describe('Unit Tests - Basic Examples', () => {
      it('should format P/VP ratios with 2 decimal places', () => {
        const result1 = formatRatio(1.0392547);
        expect(result1.displayValue).toBe('1,04');
        expect(result1.status).toBe('premium');

        const result2 = formatRatio(0.98765);
        expect(result2.displayValue).toBe('0,99');
        expect(result2.status).toBe('discount');

        const result3 = formatRatio(1.0);
        expect(result3.displayValue).toBe('1,00');
        expect(result3.status).toBe('neutral');
      });

      it('should determine status correctly', () => {
        // Premium (> 1.0)
        expect(formatRatio(1.05).status).toBe('premium');
        expect(formatRatio(1.5).status).toBe('premium');

        // Discount (< 1.0)
        expect(formatRatio(0.95).status).toBe('discount');
        expect(formatRatio(0.5).status).toBe('discount');

        // Neutral (= 1.0)
        expect(formatRatio(1.0).status).toBe('neutral');
      });

      it('should determine intensity correctly', () => {
        // High intensity outside [0.95, 1.05]
        expect(formatRatio(1.06).intensity).toBe('high');
        expect(formatRatio(0.94).intensity).toBe('high');

        // Low intensity inside [0.95, 1.05]
        expect(formatRatio(1.05).intensity).toBe('low');
        expect(formatRatio(0.95).intensity).toBe('low');
        expect(formatRatio(1.0).intensity).toBe('low');
      });

      it('should handle null and undefined', () => {
        const result1 = formatRatio(null);
        expect(result1.displayValue).toBe('—');
        expect(result1.status).toBe('neutral');

        const result2 = formatRatio(undefined);
        expect(result2.displayValue).toBe('—');
        expect(result2.status).toBe('neutral');
      });

      it('should handle NaN', () => {
        const consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
        const result = formatRatio(NaN);
        expect(result.displayValue).toBe('—');
        expect(result.status).toBe('neutral');
        consoleWarnSpy.mockRestore();
      });

      it('should provide appropriate aria labels', () => {
        const premium = formatRatio(1.1);
        expect(premium.ariaLabel).toContain('Premium');

        const discount = formatRatio(0.9);
        expect(discount.ariaLabel).toContain('Discount');

        const neutral = formatRatio(1.0);
        expect(neutral.ariaLabel).not.toContain('Premium');
        expect(neutral.ariaLabel).not.toContain('Discount');
      });
    });

    describe('Property-Based Tests - P/VP Ratio Formatting', () => {
      it('Property 4: For P/VP values from 0.5 to 2.0, formatting produces displayValue with exactly 2 decimal places', () => {
        const testValues = [0.5, 0.95, 0.98765, 1.0, 1.0392547, 1.05, 1.5, 2.0];
        testValues.forEach((value) => {
          const result = formatRatio(value);
          expect(result.displayValue).toMatch(/\d+,\d{2}/);
        });
      });

      it('Property 4: Status determination is consistent with value comparison to 1.0', () => {
        const testCases = [
          { value: 1.1, expectedStatus: 'premium' },
          { value: 1.5, expectedStatus: 'premium' },
          { value: 0.9, expectedStatus: 'discount' },
          { value: 0.5, expectedStatus: 'discount' },
          { value: 1.0, expectedStatus: 'neutral' },
        ];
        testCases.forEach(({ value, expectedStatus }) => {
          const result = formatRatio(value);
          expect(result.status).toBe(expectedStatus);
        });
      });

      it('Property 4: P/VP Ratio Formatting - Fast-check property test with minimum 100 iterations', () => {
        /**
         * **Validates: Requirement 6.1**
         * 
         * For any numeric P/VP ratio value, formatting SHALL produce output with exactly 2 decimal places
         * using round-half-up rounding, regardless of input precision.
         */
        const property = fc.property(
          fc.integer({ min: 80, max: 120 }).map(n => n / 100),
          (pvRatio: number) => {
            const result = formatRatio(pvRatio);

            // Verify displayValue matches exactly 2 decimal places pattern
            expect(result.displayValue).toMatch(/^\d+,\d{2}$/);

            // Verify status is correctly determined
            if (pvRatio > 1.0) {
              expect(result.status).toBe('premium');
            } else if (pvRatio < 1.0) {
              expect(result.status).toBe('discount');
            } else {
              // Edge case: value === 1.0
              expect(result.status).toBe('neutral');
            }

            // Verify intensity is correctly determined
            if (pvRatio > 1.05 || pvRatio < 0.95) {
              expect(result.intensity).toBe('high');
            } else {
              expect(result.intensity).toBe('low');
            }

            // Verify ariaLabel is non-empty string
            expect(result.ariaLabel).toBeDefined();
            expect(typeof result.ariaLabel).toBe('string');
            expect(result.ariaLabel.length).toBeGreaterThan(0);

            return true;
          }
        );

        fc.assert(property, { numRuns: 100 });
      });

      it('Property 4: P/VP Ratio Formatting - Edge cases for intensity determination', () => {
        /**
         * **Validates: Requirement 6.8, 6.9, 6.10, 6.11**
         * 
         * Verify intensity boundaries:
         * - For values > 1.05: intensity must be 'high'
         * - For values < 0.95: intensity must be 'high'
         * - For values in [0.95, 1.05]: intensity must be 'low'
         */
        const edgeCases = [
          { value: 1.06, expectedIntensity: 'high', expectedStatus: 'premium' },
          { value: 1.05, expectedIntensity: 'low', expectedStatus: 'premium' },
          { value: 1.04, expectedIntensity: 'low', expectedStatus: 'premium' },
          { value: 1.0, expectedIntensity: 'low', expectedStatus: 'neutral' },
          { value: 0.96, expectedIntensity: 'low', expectedStatus: 'discount' },
          { value: 0.95, expectedIntensity: 'low', expectedStatus: 'discount' },
          { value: 0.94, expectedIntensity: 'high', expectedStatus: 'discount' },
        ];

        edgeCases.forEach(({ value, expectedIntensity, expectedStatus }) => {
          const result = formatRatio(value);
          expect(result.intensity).toBe(expectedIntensity);
          expect(result.status).toBe(expectedStatus);
        });
      });

      it('Property 4: P/VP Ratio Formatting - Display value formatting verification', () => {
        /**
         * **Validates: Requirement 6.1, 6.2, 6.3**
         * 
         * Verify specific examples:
         * - formatRatio(1.0392547) must return displayValue "1,04"
         * - formatRatio(0.98765) must return displayValue "0,99"
         * - For all X in [0.8, 1.2]: displayValue matches /\d+,\d{2}/
         */
        const examples = [
          { value: 1.0392547, expectedDisplay: '1,04' },
          { value: 0.98765, expectedDisplay: '0,99' },
          { value: 1.0, expectedDisplay: '1,00' },
          { value: 0.94, expectedDisplay: '0,94' },
          { value: 1.06, expectedDisplay: '1,06' },
        ];

        examples.forEach(({ value, expectedDisplay }) => {
          const result = formatRatio(value);
          expect(result.displayValue).toBe(expectedDisplay);
        });
      });
    });
  });

  describe('Integration Tests - Formatter Interaction', () => {
    it('should handle a mix of valid and invalid inputs consistently', () => {
      const validValues = [100, 1000, 0.5, -50];
      const invalidValues = [null, undefined];

      validValues.forEach((val) => {
        expect(formatCurrency(val)).not.toBe('—');
      });

      invalidValues.forEach((val) => {
        expect(formatCurrency(val)).toBe('—');
      });
    });

    // NaN test separated since it needs mock
    it('should handle NaN in all formatters', () => {
      const consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
      expect(formatCurrency(NaN)).toBe('—');
      expect(formatPercentage(NaN)).toBe('—');
      expect(formatRatio(NaN).displayValue).toBe('—');
      consoleWarnSpy.mockRestore();
    });
  });
});
